services:
  backend:
    build: ./backend
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=riceshop
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/public/uploads:/app/public/uploads
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=riceshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    restart: unless-stopped

  admin:
    build: ./admin
    ports:
      - "3002:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
